kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: zabbix
  name: mysql-pv-volume
  labels:
    type: local
    app: mysql-server
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql