apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: zabbix
  labels:
     zabbix-app: zabbix-agent
  name: zabbix-agent-claim
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi