kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: zabbix
  name: mysql-pv-claim
  labels:
    app: mysql-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi