apiVersion:  apps/v1
kind: StatefulSet
metadata:
  namespace: zabbix
  labels:
    zabbix-app: zabbix-server
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      zabbix-app: zabbix-server  
  serviceName: "zabbix-server"
  template:
    metadata:
      labels:
        zabbix-app: zabbix-server
    spec:
      containers:
      - image: zabbix/zabbix-server-mysql:6.2.7-alpine
        name: zabbix-server
        env:
          - name: ZBX_STARTHTTPPOLLERS
            valueFrom:
              configMapKeyRef:
                key: ZBX_STARTHTTPPOLLERS
                name: zabbix-app
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-app
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: MYSQL_DATABASE
                name: zabbix-app
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-app
                key:  MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-app
                key:  MYSQL_PASSWORD
        ports:
        - containerPort: 10051
        resources: {}
      restartPolicy: Always