apiVersion: v1
kind: Service
metadata:
  namespace: zabbix
  labels:
    zabbix-app: zabbix-frontend
  name: zabbix-frontend
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    zabbix-app: zabbix-frontend