apiVersion: v1
kind: Service
metadata:
  namespace: zabbix
  labels:
    zabbix-app: zabbix-server
  name: zabbix-server
spec:
  ports:
  - name: "10051"
    port: 10051
    targetPort: 10051
  selector:
    zabbix-app: zabbix-server